version: '3'
services:
  database:
    image: postgres
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/database
    environment:
      - POSTGRES_DB=booksDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123