version: '3'
services:
  database:
    image: postgres
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  - ./database # this helps to persist the data even after the service is shut down